language: python
dist: xenial
matrix:
  include:
    - python: '3.6'
    - python: '3.7'
      env: UPLOAD=True
    - python: 3.7-dev
install:
  - pip install .[test]
script: echo hello world
deploy:
  provider: pypi
  distributions: sdist
  user: mara-pypi-upload-account
  password:
    secure: Y4eCz/P64+6yhyoapZMoCgVKaJWGvDvbBugRAqiYeoSoJu/1Pex1alCvQZvJ4Uw0n5Pu3TUlmhiSombBxslusRzXU2raynyVpL1nfhTQ2tjtT/C+AS8OaDwjbNLhCgHauc8PjcbmfMC+kzI/XAuSdFueRw1SwfsHKcr4g1FexJa++HJeXxwhElZfA82M5HYDx4F/DzEW0SYSa9F03CMLlnIpMrUyN2opnWaRutpgB0OT5gm1sXjiNzitaQIbVmopPczbRM0xlhMf+Il2zdVSWQ1jAp8TaukpWe0nBCfgDNchyknNNVbJotzWgDWutHdcjCSLm3VqXnqsx7qqpNTs0QoG7w+rKtA7YlAo5i8d2fVaXiaUHvPDsdHmWUf/9E/dr3ll/lzVyPrsRnf6tsbXTX9BAJ2oE+XN0s2p30oH2szjZziXSySLHPVE4kC3LYQ4tU4C6pQyzppyrkByMpbyuVC6K4mhwAYjGpapTQn7ulIIWFIvWUpsQGFagQ/shaJk0CFYPgD9DoWRIlWDrpY9I1St1GRsi7NwLpywJD5ME66EWoolTJUvOsln7jJcs5pLjf2Y53LbtZ0cjtQsttU7Pm7je4+Y5B8um+OrTaj8s74gOsLawkgGOFfk1WMsCAcw4xmto+vwVBwrvtYgIwuFo3O3TG/QhsHFGLAuo5RDOoo=
  on:
    tags: true
    branch: master
    repo: mara/mara-db
    condition: "$UPLOAD == True"
